config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => 'home#top'
  get 'home/about' => 'home#about'
  resources :users, only: [:index, :show, :create, :edit, :update]
  resources :relationships, only: [:index, :create, :destroy]
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :books, only: [:index, :show, :create, :edit, :update, :destroy] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  get 'search' => 'search#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  validates :title, presence: true
  validates :body, presence: true
  validates :body,    length: { maximum: 200 }

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.search(search, word)
    if search == "perfect_match"
      @book = Book.where(title: "#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE ?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE ?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE ?","%#{word}%")
    else
      @book = Book.all
    end
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  validates :name, presence: true
  validates :name,    length: { in: 2..20 }
  validates :introduction,    length: { maximum: 50 }

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user

  attachment :profile_image

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

  def self.search(search,word)
    if search == "perfect_match"
      @user = User.where(name: "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE ?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE ?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE ?","%#{word}%")
    else
      @user = User.all
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    flash[:notice] = "Signed in successfully."
    user_path(current_user)
  end

  protected

  def configure_permitted_parameters
    added_attrs = [ :email, :username, :password, :password_confirmation ]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user,{only: [:edit, :update]}

def ensure_correct_user
  @book = Book.find(params[:id])
  if current_user.id != @book.user.id
   redirect_to books_path
  end
end

  def index
    @books = Book.all
    @user = User.find(current_user.id)
    @book = Book.new
  end

  def show
    @books = Book.all
    @book = Book.new
    @user = User.find(current_user.id)
    @book_s = Book.find(params[:id])
    @book_comment = BookComment.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have creatad book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user = User.find(current_user.id)
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render 'edit'
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_back(fallback_location: books_path)
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back(fallback_location: books_path)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def top
  end

  def about
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def search
    @range = params[:range]
    search = params[:search]
    word = params[:word]
    @word = word

    if @range == '1'
      @user = User.search(search,word)
    else
      @book = Book.search(search,word)
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user,{only: [:edit, :update]}

  def ensure_correct_user
    @user = User.find(params[:id])
    if current_user.id != @user.id
      redirect_to user_path(current_user.id)
    end
  end

  def index
    @users = User.all
    @books = Book.all
    @user = User.find(current_user.id)
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have creatad book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render 'index'
    end
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render 'edit'
    end
  end

  def following
    @title = "Follow Users"
    @user = User.find(params[:id])
    @users = @user.followings
    render 'show_follow'
  end

  def followers
    @title = "Follower Users"
    @user = User.find(params[:id])
    @users = @user.followers
    render 'show_follow'
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookers2</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

  <header>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarEexample1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <p class="navbar-brand">Bookers</p>
        </div>
        <div class="collapse navbar-collapse" id="navbarEexample1">
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
            <li>
              <%= link_to user_path(current_user.id) do %>
              <span class="glyphicon glyphicon-home"> Home </span>
              <% end %>
            </li>
            <li>
              <%= link_to users_path do %>
              <span class="glyphicon glyphicon-user"> Users </span>
              <% end %>
            </li>
            <li>
              <%= link_to books_path do %>
              <span class="glyphicon glyphicon-book"> Books </span>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
              <span class="glyphicon glyphicon-log-out"> logout </span>
              <% end %>
            </li>
            <% else %>
            <li>
              <%= link_to root_path do %>
              <span class="glyphicon glyphicon-home"> Home </span>
              <% end %>
            </li>
            <li>
              <%= link_to '/home/about' do %>
              <span class="glyphicon glyphicon-link"> About </span>
              <% end %>
            </li>
            <li>
              <%= link_to new_user_registration_path do %>
              <span class="glyphicon glyphicon-edit"> sign up </span>
              <% end %>
            </li>
            <li>
              <%= link_to new_user_session_path do %>
              <span class="glyphicon glyphicon-log-in"> login </span>
              <% end %>
            </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <% if flash[:notice] %>
    <div class="alert alert-success">
      <%= flash[:notice] %>
    </div>
    <% end %>
    <% if flash[:alert] %>
    <div class="alert alert-danger">
      <%= flash[:alert] %>
    </div>
    <% end %>

    <% unless current_page?(root_path) %>
    <% unless request.path.include?("home") %>
    <% if user_signed_in? %>
    <div class="text-center">
      <br>
      <%= form_tag(search_path, method: :get) do %>
      <%= text_field_tag (:word) %>
      <%= select_tag 'range' ,options_for_select([['User', '1'], ['Book', '2']]) %>
      <%= select_tag 'search', options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"], ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
      <%= submit_tag "検索" %>
      <% end %>
    </div>
    <% end %>
    <% end %>
    <% end %>

  </header>

  <%= yield %>

  <footer>
    <div class="container">
      <div class="row">
        <div class="col-md-offset-9 col-md-3">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>
  </footer>
</body>
</html>

app/views/template/_book_list.html.erb
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
    <tr>
      <td style="width:10%">
        <%= link_to user_path(book.user.id) do %>
        <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40', class: "pull-left profile-thumb" %>
        <% end %>
      </td>
      <td style="width:20%"><%= link_to book_path(book.id) do %><%= book.title %><% end %></td>
      <td style="width:49%"><%= book.body %></td>
      <% if book.favorited_by?(current_user) %>
      <td style="width:6%">
        <%= link_to book_favorites_path(book), method: :delete do %>
        <span class="glyphicon glyphicon-heart" style="color: red;"></span>
        <%= book.favorites.count %>
        <% end %>
      </td>
      <% else %>
      <td style="width:6%">
        <%= link_to book_favorites_path(book), method: :post do %>
        <span class="glyphicon glyphicon-heart-empty"></span>
        <%= book.favorites.count %>
        <% end %>
      </td>
      <% end %>
    <td style="width:15%">コメント数：<%= book.book_comments.count %>
    </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/template/_new_book.html.erb
<h2>New book</h2>
<%= form_for(book, url: books_path) do |f| %>
<p>Title</p>
<%= f.text_field :title, class:"form-control" %>
<br>
<p>Opinion</p>
<%= f.text_area :body, class:"form-control", rows:"3" %>
<br>
<%= f.submit "Create Book", class:"btn btn-primary col-xs-12" %>
<% end %>

app/views/template/_user_info.html.erb
<div class="clearfix">
  <h2>User info</h2>
  <%= attachment_image_tag user, :profile_image, :fill, 120, 120, format: 'jpeg', class: "profile-img", fallback: "no_image.jpg" %>
  <br>
  <table class="table">
    <tbody>
      <tr></tr>
      <tr>
        <td>name</td>
        <td class="overflow-wrap-break"><%= user.name %></td>
      </tr>
      <tr>
        <td>introduction</td>
        <td class="overflow-wrap-break"><%= user.introduction %></td>
      </tr>
      <tr>
        <td>follows</td>
        <td class="overflow-wrap-break">
          <%= link_to following_user_path(user.id) do %>
          <%= user.followings.count %>
            <% end %>
          </td>
      </tr>
      <tr>
        <td>followers</td>
        <td class="overflow-wrap-break">
          <%= link_to followers_user_path(user.id) do %>
          <%= user.followers.count %>
            <% end %>
        </td>
      </tr>
    </tbody>
  </table>
  <% if user.id == current_user.id %>
  <%= link_to edit_user_path(user) do %>
  <button type="button" class="btn btn-default col-xs-12" aria-label="Left Align"><span class="glyphicon glyphicon-wrench" aria-hidden="true"></span></button>
  <% end %>
  <% end %>
</div>
<% unless current_user == user %>
<% if current_user.following?(user) %>
<%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
<%= hidden_field_tag :follow_id, user.id %>
<%= f.submit 'フォロー外す', class: 'btn btn-primary btn-block' %>
<% end %>
<% else %>
<%= form_for(current_user.relationships.build) do |f| %>
<%= hidden_field_tag :follow_id, user.id %>
<%= f.submit 'フォローする', class: 'btn btn-success btn-block' %>
<% end %>
<% end %>
<% end %>

app/views/template/_user_list.html.erb
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th style="width:15%">image</th>
      <th style="width:15%">name</th>
      <th style="width:15%"></th>
      <th style="width:20%"></th>
      <th style="width:10%"></th>
      <th style="width:25%"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
    <tr>
      <td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", size:'60x60', class: "pull-left profile-thumb" %></td>
      <td><%= user.name %></td>
      <td>フォロー数：<%= user.followings.count %></td>
      <td>フォロワー数：<%= user.followers.count %></td>
      <td>
        <% unless current_user == user %>
        <% if current_user.following?(user) %>
        <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
        <%= hidden_field_tag :follow_id, user.id %>
        <%= f.submit 'フォロー外す', class: 'btn btn-xs btn-primary btn-block' %>
        <% end %>
        <% else %>
        <%= form_for(current_user.relationships.build) do |f| %>
        <%= hidden_field_tag :follow_id, user.id %>
        <%= f.submit 'フォローする', class: 'btn btn-xs btn-success btn-block' %>
        <% end %>
        <% end %>
        <% end %>
      </td>
      <td><%= link_to user_path(user.id) do %>Show<% end %></td>
    </tr>
    <% end %>
  </tbody>
</table>